### ISSUE TITLE
Allow file prefix, file suffix or even file pattern

### ISSUE THREAD

**Issue by tzi** [M6Web/bemlinter#2]
The bem linter get the block name from the file name.
We should authorize prefix in file name, like `project-block.scss`, or suffix, like `block.theme.scss`.

So should we create two properties?
 * filePrefix: `['', 'project-']` default `['']`
 * fileSuffix: `['.scss', '.theme.scss']` default `['.scss']`

Or should we create only one option named `filePattern`?

**Comment by fdubost** [comment]
`filePattern` is maybe more flexible 🌴

**Comment by tzi** [comment]
Yes! But I don't know how to write it :disappointed: 

 * A list of pattern would be complex: `['*.scss', 'project-*.scss', '*.theme.scss', 'project-*.theme.scss']`
 * A to know what to catch with a regexp: `(project-)?([^.]*)(\.theme)?\.scss`

**Comment by fdubost** [comment]
Regexp is maybe a little tricky to write but it's a standard and the best way for me 🐤

**Comment by fdubost** [comment]
👍 💪
